save: experiments/
dataset: Dataset_LE_1City_4Age
num_cities: 1
num_ages: 4
loss_level: age
epochs: 154
training_time: 50
validation_time: 15
lr: 8.0e-05
warmup_epochs: 1000
patience: 20
grad_clip: 1.0
lr_factor: 0.8
ic_weight: 1.0
random_seed: 9
device: cuda:0
gl_num_layers: 5
gl_hidden_dim: 64
c_hidden_dim: 10
re_factor: 0.0001
gamma: 0.02
pop_ref: 1000000.0
mob_hidden_dim: 128
mob_num_layers: 4
mob_ckpt_path: ''
