save: experiments/
dataset: Hubei_3City_1Age
num_cities: 3
num_ages: 1
loss_level: age
epochs: 414
training_time: 15
validation_time: 5
lr: 8.0e-05
warmup_epochs: 1000
patience: 30
grad_clip: 1.0
lr_factor: 0.8
ic_weight: 40.0
device: cuda:0
gl_hidden_dim: 64
gl_num_layers: 10
c_hidden_dim: 9
random_seed: 9
re_factor: 0.0001
gamma_init:
- 0.1
- 0.78
- 0.76
sigma: 0.1923076923076923
alpha_E_init: 22500.0
eps_E_init: 0.0001
pop_ref: 5000000.0
mob_hidden_dim: 256
mob_num_layers: 15
mob_ckpt_path: ''
S0_lr_factor: 0.25
E0_lr_factor: 1.5
I0_lr_factor: 1.5
gamma_lr_factor: 3.0
use_lr_increase: true
lr_increase_start: 500
lr_increase_every: 250
lr_increase_factor: 2
lr_max: 0.0001
contact_values: 65,14,66
s0_ratio: 1.0
i0_min: 0.0
s0_values: 120000,10000,9000
e0_values: 22,3,5
i0_values: 520,1,1
r0_values: 0, 0, 0
rho_src: 3.0
rho_dst: 10.0
alpha_grav: 0.2
beta_grav: 1.8
lambda_grav: 0.003
city_names:
- "\u6B66\u6C49\u5E02"
- "\u5B5D\u611F\u5E02"
- "\u9EC4\u5188\u5E02"
static_pop_city_raw:
- 12326518.0
- 4270371.0
- 5882719.0
